export enum EventType{
    DOOR_OPENED="DOOR_CLOSED",
    DOOR_CLOSED="DOOR_CLOSED",
    DOOR_ALARM="DOOR_ALARM",
    UNLOCK_REQUEST="UNLOCK_REQUEST",
    UNLOCK_DENIED="UNLOCK_DENIED",
    UNLOCK_EVENT="UNLOCK_EVENT",
    KEY_BLOCKED="KEY_BLOCKED",
    KEY_USED="KEY_USED",
    KEY_BLOCKED_WAS_USED="KEY_BLOCKED_WAS_USED",
}